export const photos = [
    {
      id:1,
      Image:'https://bootstrapmade.com/demo/templates/PhotoFolio/assets/img/gallery/gallery-1.jpg'
    },
    {
      id:2,
      Image:'https://bootstrapmade.com/demo/templates/PhotoFolio/assets/img/gallery/gallery-2.jpg'
    },
    {
      id:3,
      Image:'https://bootstrapmade.com/demo/templates/PhotoFolio/assets/img/gallery/gallery-3.jpg'
    },
    {
      id:4,
      Image:'https://bootstrapmade.com/demo/templates/PhotoFolio/assets/img/gallery/gallery-4.jpg'
    },
    {
      id:5,
      Image:'https://bootstrapmade.com/demo/templates/PhotoFolio/assets/img/gallery/gallery-5.jpg'
    },
    {
      id:6,
      Image:'https://bootstrapmade.com/demo/templates/PhotoFolio/assets/img/gallery/gallery-6.jpg'
    },
    {
      id:7,
      Image:'https://bootstrapmade.com/demo/templates/PhotoFolio/assets/img/gallery/gallery-7.jpg'
    },
    {
      id:8,
      Image:'https://bootstrapmade.com/demo/templates/PhotoFolio/assets/img/gallery/gallery-8.jpg'
    },
    {
      id:9,
      Image:'https://bootstrapmade.com/demo/templates/PhotoFolio/assets/img/gallery/gallery-9.jpg'
    },
    {
      id:10,
      Image:'https://bootstrapmade.com/demo/templates/PhotoFolio/assets/img/gallery/gallery-10.jpg'
    },
    {
      id:11,
      Image:'https://bootstrapmade.com/demo/templates/PhotoFolio/assets/img/gallery/gallery-11.jpg'
    },
    {
      id:12,
      Image:'https://bootstrapmade.com/demo/templates/PhotoFolio/assets/img/gallery/gallery-12.jpg'
    },
    {
      id:13,
      Image:'https://bootstrapmade.com/demo/templates/PhotoFolio/assets/img/gallery/gallery-13.jpg'
    },
    {
      id:14,
      Image:'https://bootstrapmade.com/demo/templates/PhotoFolio/assets/img/gallery/gallery-14.jpg'
    },
    {
      id:15,
      Image:'https://bootstrapmade.com/demo/templates/PhotoFolio/assets/img/gallery/gallery-15.jpg'
    },
    {
      id:16,
      Image:'https://bootstrapmade.com/demo/templates/PhotoFolio/assets/img/gallery/gallery-16.jpg'
    },
]